### ISSUE TITLE
Engines or Battery Switches Not Syncing

### ISSUE THREAD

**Issue by michaelmagdy15** [Sequal32/yourcontrol#11]
So Me and my friend were in the same aircraft c172 specifically andc the TBM 930 Same Issue
When i turn the Battery On It does not Sync on his end Same Thing With Engine start Key 
also The Propeller Seems To Be static When We are connected its pretty Funny But Yeah man Great Start Cant Wait for the Update <3
Please add a Donation Area i wanna pledge in !

**Comment by MoritzT** [comment]
Can confirm, same happened in the 172 skyhawk 6 pack. Bat switch was in for the client even though it was off on the server. Magnetos were not synced either.

**Comment by Sequal32** [comment]
Appreciate the feedback! As a quick fix, open up `sync_bools.dat` and delete the lines that say `ELECTRICAL MASTER BATTERY` and `GEAR HANDLE POSITION` as those are problematic with SimConnect. This should've been included in the latest release but silly me forgot to include it in. As for the engine starter - I am working on a rewrite that will enable many more switches to be synced.

**Comment by michaelmagdy15** [comment]
**Thank Yo So Much <3**
