### ISSUE TITLE
Controls break when passing controls while on AP

### ISSUE THREAD

**Issue by MoritzT** [Sequal32/yourcontrol#12]
So I tested this today and while in cruise on AP with ALT and NAV engaged in a 172 skyhawk I passed controls to the client and the plane started to rotate out of control as it didn't seem to be on AP or have the full plane config synced. I also noticed that when I pass controls the client plane jumped a bit forward and we were not in the same position anymore.

Happy to provide more details if needed

**Comment by Sequal32** [comment]
Thanks for the feedback! I'll look into fixing this for the next release.
