### ISSUE TITLE
Light switches not syncing

### ISSUE THREAD

**Issue by samuelcardillo** [Sequal32/yourcontrol#13]
Light switches in many aircraft (TBM, A320 neo, ...) are not syncing at all. We keep having to do weird stuff to make them sync but most of the time it is near impossible.

**Comment by Sequal32** [comment]
Thanks for the feedback! Many of the switches in the aircraft are not exposed to SimConnect, but in the next release, they'll be a way to get those switches synced so stay tuned for that within the next month or two.

**Comment by Sequal32** [comment]
Thanks for the feedback! Light switches should be the one thing that sync. If not, I'll take a further into it for next release.

**Comment by Sequal32** [comment]
Try out the new version and let me know how that goes. All switches in the C172 should now be synced.
