### ISSUE TITLE
I put the ip and the port and it won't let me join my friend

### ISSUE THREAD

**Issue by mariocmg** [Sequal32/yourcontrol#14]
I put the ip and the port and it won't let me join my friend

**Comment by Sequal32** [comment]
Have you got the port forwarded?

**Comment by mariocmg** [comment]
Yes

**Comment by Sequal32** [comment]
Try out the new version and let me know how that goes, closing this for now. You can also start up the server, then use a website like https://www.yougetsignal.com/tools/open-ports/ to verify that the port is forwarded. Make sure you've allowed the program through your firewall as well.
