### ISSUE TITLE
Debug mode / logs

### ISSUE THREAD

**Issue by MoritzT** [Sequal32/yourcontrol#17]
Hey,

I am looking into adding some sync vars, but I am not familiar with Rust. How can I run the program with some debugging/logging to test changes locally?

**Comment by Sequal32** [comment]
I haven't implmented any form of logging for the program but if you follow the same formats as the `.dat` files then eventually you may be able to find a way. The `sync_bools.dat` is very limited in functionality and is used only for the initial synchronization so not sure how much that'll help you. Next release will have a bunch of files that can easily be modified.

**Comment by MoritzT** [comment]
Yes, I played around with adding sync for COM1 and NAV1 and I eventually made it work including some adjustments to SPAD.Next which used different events to change frequencies. I can send a pull request tomorrow, if it's worth it with the upcoming changes.

The only issue I couldn't get sorted was syncing frequencies on initial connect/re-connect.

**Comment by MoritzT** [comment]
Also I don't know if that's possible, but it would be great to have a way where the co-pilot not in active control can still change some switches, like gear up/down, flaps, radios.

**Comment by Sequal32** [comment]
Awesome! I'd love to see your PR then. The co-pilot should be able to change flaps and switches already, so that's another thing to look into I guess...

**Comment by MoritzT** [comment]
At one point he could do gear up, but with my latest "fixes" for the radios he couldn't make those changes and even when I passed controls it was not syncing it back to the server. Will send the PR, but it might require some additional testing/review from your end

**Comment by Sequal32** [comment]
The new version makes it a lot easier to add more sim vars and sim events, so adding more sync-able switches should be fairly easy. Take a look at `C172.yaml` for an example.
