### ISSUE TITLE
2 planes?

### ISSUE THREAD

**Issue by k2gremlin** [Sequal32/yourcontrol#18]
Hello Sequal, 

When trying this out with a friend, we were able to get connected and with him as the active, my plane was being towed around by him. Almost like my plane was on a rope. How do we get it synced so were the same plane? Below is the settings we used. 
  "port": 7777,
  "update_rate": 20,
  "buffer_size": 3,
  "conn_timeout": 20.0,

**Comment by k2gremlin** [comment]
http://prntscr.com/uks0h5 is an example.

**Comment by MoritzT** [comment]
I can confirm. We had that happening today as well

**Comment by Sequal32** [comment]
Due to latency, this is not possible. The idea isn't really to sync up positions to the millisecond, rather it's to help each other with the instruments and radios while seemingly flying the same aircraft.

**Comment by MoritzT** [comment]
We ended up using 2 different servers in MFS which does not impact yourcontrol, but avoids seeing a 'ghost' plane in front/behind you

**Comment by michaelmagdy15** [comment]
@MoritzT Just set Your Multiplayer to Group Only
