### ISSUE TITLE
This Might Help You :)

### ISSUE THREAD

**Issue by michaelmagdy15** [Sequal32/yourcontrol#20]
Hey Bro Long Time no see lol

Anyways i found some usefull info for you from the New SDK From The Sim Maybe You Can Check it Out They even added a Huge Chunk Of Simconnect Info !
[SimConnect_Status_of_SimEvents.html.pdf](https://github.com/Sequal32/yourcontrol/files/5308453/SimConnect_Status_of_SimEvents.html.pdf)

**Comment by Sequal32** [comment]
Yup, that's from the SDK so I've already taken a look through all of them. Thanks though.
