### ISSUE TITLE
Connecting Error

### ISSUE THREAD

**Issue by Vismaypikachu** [Sequal32/yourcontrol#21]
Client disconnected reason connection timed is the error I get. Is there a fix

**Comment by Sequal32** [comment]
Not a bug. Connection timed out means that you couldn't connect to the server, so the person running the server didn't set up things correctly. Refer to the following resources for port forwarding:

Check out this video for a tutorial:
https://www.youtube.com/watch?v=usSpl0yJFnY.
You can find specific instructions for your router here: https://portforward.com/router.htm
Alternatively look into this software if you're not able to completely figure it out: https://github.com/kaklakariada/portmapper.
Finally if you cannot port forward check out this tutorial on Hamachi:
https://www.youtube.com/watch?v=bWbo0gcFqA8
