### ISSUE TITLE
1.2.0 - Starting exe goes straight to Not Responding

### ISSUE THREAD

**Issue by rmroc451** [Sequal32/yourcontrol#3]
I downloaded the latest version, but upon opening it, it goes straight into a "not responding" state and you can't interact with it.

I looked for any logs I could provide, or discern for myself, but I don't see any.

**Comment by Sequal32** [comment]
Thanks for reporting this! Resolved in 8f4c47a0e5eccc45822dd7f0d7e45eb1f4098a2c.
