### ISSUE TITLE
.exe missing

### ISSUE THREAD

**Issue by EpicPrimus** [Sequal32/yourcontrol#4]
.exe is not avaiable in the latest update.

**Comment by Sequal32** [comment]
Not sure what you mean - `sharedcockpit.exe` should be included in the zip file, along with its other file dependencies.

**Comment by EpicPrimus** [comment]
There is no .exe file for me and some other people tried to download. Tried to download different releases, but it´s just not there^^ Thanks

**Comment by Sequal32** [comment]
That's really strange... here's a direct [link](https://github.com/Sequal32/yourcontrol/releases/download/v1.2.1/sharedcockpit.zip) to the latest release as of now. It's a zip file so you'll have to extract it, and the exe will be inside of it.
