### ISSUE TITLE
TBM FMC not syncing flight plan

### ISSUE THREAD

**Issue by LandonPatmore** [Sequal32/yourcontrol#8]
Version: `1.2.4`
Aircraft: TBM

Looks like navigating through the menus on the bottom screen (MFD, PFD, and COMMS) is not synced.  When entering waypoints, the GPS on my screen shows the route, but on my friend's it does not.

Is this a limitation of simconnect as well?

**Comment by Sequal32** [comment]
Yeah, there's a bunch of things SimConnect can't do... Perhaps there's a way to hook into the javascript of all the various systems and sync them up through there.

**Comment by LandonPatmore** [comment]
Funny enough, I was just thinking of that.  The only problem I can see is the fact that each aircraft has its own FMC system (some have the same).  That would mean each aircraft's FMC would need to be modified.  Because an A320's FMC is completely different from a TBM's.

I can take a look into this today.  This will be interesting for sure.

**Comment by LandonPatmore** [comment]
Hoping there is some type of interface they use to standardize the data though.

**Comment by Sequal32** [comment]
I don't think so. Took a look through that stuff today, seems like everything is kept in javascript. We'll need to pipe function calls out with individual system names and parameters somehow.

**Comment by LandonPatmore** [comment]
Looks like the files to look for are in `asobo-vcockpits-instruments-navsystems\html_ui\Pages\VCockpit\Instruments\NavSystems\AS1000\` folder.  That gives a good start.  Looks like a lot of it is shared based on the type of navigation equipment, not on the aircraft itself.  That makes it a bit easier.

**Comment by LandonPatmore** [comment]
Actually for the TBM, its the `AS3000` folder

**Comment by Sequal32** [comment]
Yup, any ideas to modify the javascript in order to pipe them two way to an external program? Modifying the javascript files may be the only way... Not sure if using a websocket/socket connection is viable either.

**Comment by Sequal32** [comment]
Okay I found out that the navsystems and basically everything else uses LVARs that can be accessed by a gauge within the sim. Unfortunately I cannot directly access them from an external program like this. I'll create a C gauge to pipe information between the shared cockpit program and the aircraft. This would be way simpler than intercepting JS calls haha.

**Comment by Sequal32** [comment]
^ That has been implemented in the new version. However, I don't believe it's possible to sync the FMCs due to them relying on `H:` events. I haven't found a way to detect when they change.

**Comment by LandonPatmore** [comment]
`H:` events?  Also good to see you got it working!

**Comment by Sequal32** [comment]
Yeah they’re events defined by the gauge and not by the simulator itself. The simulator uses K: events (key) while the AS1000 and other fmcs uses their own defined H: (no clue what it stands for) events which I can’t find any way to listen to as it’s defined by the gauge and doesn’t change any local variables either.
