### ISSUE TITLE
This isnt a Issue This is a Thank You!

### ISSUE THREAD

**Issue by michaelmagdy15** [Sequal32/yourcontrol#9]
**I STUMBLED ACROSS YOUR REPO AND I WAS JUST AMAZED BECAUSE I HAVE BEEN WAITING FOR THE SHARED COCKPIT FEATURE TO BE OUT SOONER BUT YUP YOU WIN MAN!**

**I WANNA HELP YOU MAKE THIS HUGE SO I MADE A VIDEO ABOUT IT ON MY CHANNEL AND SHARED THE HELL OF IT** https://youtu.be/54t0nT768YM
"YOU Can Share Cockpits Now With This Mod😍"

_PLEASE LET ME DONATE MY 5 BUCKS OF THANK YOU! ❤_

Regards,
Michael or FSMADDNESSPILOT

**Comment by Sequal32** [comment]
Haha glad you found this! Appreciate you sharing this around! I'd love to show more people this. Let me know if you find any more issues!
